# Generated by Django 3.1.2 on 2020-10-23 03:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Writing',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('credits', models.TextField()),
            ],
        ),
        migrations.AlterField(
            model_name='hello',
            name='photo',
            field=models.ImageField(upload_to='media'),
        ),
        migrations.AlterField(
            model_name='hellolink',
            name='hello',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='links', to='website.hello'),
        ),
        migrations.AlterField(
            model_name='performance',
            name='resume',
            field=models.ImageField(upload_to='media'),
        ),
        migrations.AlterField(
            model_name='performancelink',
            name='performance',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='links', to='website.performance'),
        ),
        migrations.CreateModel(
            name='WritingLink',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=128)),
                ('link', models.URLField()),
                ('writing', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='links', to='website.writing')),
            ],
        ),
    ]
