apiVersion: v1
kind: Service
metadata:
  name: postgres
  namespace: breton
spec:
  ports:
  - port: 5432
    targetPort: 5432
  selector:
    app: postgres
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: postgres
  namespace: breton
spec:
  selector:
    matchLabels:
      app: postgres
  serviceName: postgres  
  template:
    metadata:
      labels:
        app: postgres
    spec:
      containers:
      - name: postgres
        image: postgres:13.0
        env:
        - name: POSTGRES_DB
          value: breton
        - name: POSTGRES_PASSWORD
          valueFrom:
            secretKeyRef:
              name: breton-credentials
              key: pg-pass
        ports:
        - containerPort: 5432
        resources:
          limits:
            memory: 500Mi
            cpu: 400m
          requests:
            memory: 500Mi
            cpu: 200m
        volumeMounts:
        - name: postgres-data
          mountPath: /data
  volumeClaimTemplates:
  - metadata:
      name: postgres-data
    spec:
      accessModes:
      - ReadWriteOnce
      storageClassName: do-block-storage
      resources:
        requests:
          storage: 5Gi
