name: Auto-Release

on:
  release:
    types: [published]
    paths:
    - 'breton/**'
    - 'website/**'
    - '.dockerignore'
    - 'Dockerfile'
    - 'Pipfile.lock'
    - 'collect-and-migrate.sh'
    - '.github/auto-release.yml'

  push:
    branches:
    - master
    paths:
    - 'breton/**'
    - 'website/**'
    - '.dockerignore'
    - 'Dockerfile'
    - 'Pipfile.lock'
    - 'collect-and-migrate.sh'
    - '.github/auto-release.yml'

jobs:
  push_to_registry:
    name: Push Docker image to GitHub Packages
    runs-on: ubuntu-latest

    steps:
    - name: Check out the repo
      uses: actions/checkout@v2

    - name: Setup Python 3.9
      uses: actions/setup-python@v1
      with:
        python-version: 3.9

    - name: Install dependencies
      run: |
        python -m pip install -U pipenv
        python -m pipenv lock -r > requirements.txt

    - name: Push to GitHub Packages
      uses: docker/build-push-action@v1
      with:
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}
        registry: docker.pkg.github.com
        repository: sventi555/breton/breton
        tag_with_ref: true

  update_cluster:
    name: Update image version on StatefulSet and wait for completion
    if: github.event_name == 'release'
    needs: [push_to_registry]
    runs-on: ubuntu-latest

    steps:
    - name: Save DigitalOcean Kubernetes Config
      uses: matootie/dokube@v1.3.1
      with:
        personalAccessToken: ${{ secrets.DIGITALOCEAN_ACCESS_TOKEN }}
        clusterName: sventis-cluster
        namespace: breton

    - name: Get version
      id: gv
      run: echo "::set-output name=version::${GITHUB_REF##*/}"

    - name: Update StatefulSet
      run: kubectl patch statefulset.apps/breton -p '{"spec": {"template": {"spec": {"initContainers":[{"name":"collect-and-migrate", "image":"docker.pkg.github.com/sventi555/breton/breton:${{ steps.gv.outputs.version }}"}], "containers":[{"name":"breton", "image":"docker.pkg.github.com/sventi555/breton/breton:${{ steps.gv.outputs.version }}"}]}}}}'

    - name: Wait for StatefulSet
      run: kubectl rollout status statefulset/breton -w
